apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/testkubergl/ci-web
      context: ./web/
      jib: {}
    - image: gcr.io/testkubergl/ci-frontend
      context: ./frontend/
      jib: {}

deploy:
  kubectl:
    manifests:
      - ./web/k8s/*
      - ./frontend/k8s/*
#      - ./k8s/*y

#portForward:
#  - resourceType: deployment
#    resourceName: searcher
#    port: 8080
#    localPort: 9000

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
