server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:localhost}:3306/k8s_java
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api

#  profiles:
#    active: test